### ISSUE TITLE
Weapons without hold fire only shoot once.

### ISSUE THREAD

**Issue by GrismarPickles** [relaxtakenotes/rdrm#4]
As the title says, weapons that do not continuously fire when you hold the attack button only fire once and won't hit multiple targets. I made a little clip showing what I mean here: https://www.youtube.com/watch?v=IGdSJu5Pyq4 

The weapon I was using was from the Breen's Private Reserve mod, and most of the automatic weapons from that mod seem to work well enough (most).

**Comment by relaxtakenotes** [comment]
first of all disable sv_tfa_soundscale
second i'll check it out
