### ISSUE TITLE
Killcam occasionally does not go away after a short time

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [relaxtakenotes/rdrm#5]
When the killcam is triggered, sometimes the game will get stuck with the killcam permanently active, persisting even through player deaths and respawns, as well as admin cleanups. When this happens, a lua error is thrown several times per second:

```
lua/autorun/client/cl_rdrm_killcam.lua:31: Tried to use a NULL entity!
  1. GetPos - [C]:-1
    2. set_random_angle - lua/autorun/client/cl_rdrm_killcam.lua:31
      3. func - lua/autorun/client/cl_rdrm_killcam.lua:105
        4. execute_events - lua/autorun/client/cl_rdrm.lua:158
          5. v - lua/autorun/client/cl_rdrm_killcam.lua:142
            6. unknown - lua/includes/modules/hook.lua:96
```

**Comment by relaxtakenotes** [comment]
no mod collection. please include it in the report, unless you have received this issue without any mods enabled
